### ISSUE TITLE
Helper scripts remove existing references to statments

### ISSUE THREAD

**Issue by tarrow** [SuLab/WikidataIntegrator#15]
It should be good if we didn't make edits like this:
https://www.wikidata.org/w/index.php?title=Q27303053&diff=prev&oldid=503910825

We removed a reference that was already there (to the OpenCitations corpus).

We also update the retrieved time from EuPMC every request. We should probably only do this if the time difference is > n days. So that we aren't just spam changing

**Comment by stuppie** [comment]
@tarrow 
Regarding updating retrieved time every request, I added a new feature that allows you to pass in a function that determines if a new reference should be used or to keep the old reference. This is the ref_comparison_f and global_ref_mode options [here](https://github.com/SuLab/WikidataIntegrator/blob/master/wikidataintegrator/wdi_core.py#L53). 

This is implemented for PubmedItem [here](https://github.com/SuLab/WikidataIntegrator/blob/master/wikidataintegrator/wdi_helpers.py#L412), I'm using a function (custom_ref_equal_dates) that only updates the reference retrieved time if its older than 6 months. 

Regarding removing existing refs, we can change the global ref mode to STRICT_KEEP_APPEND, but that will then instead of updating the retrieved time, create a new reference with the new retrieved time. I'll think about this...

**Comment by Daniel-Mietchen** [comment]
I've just started #25 to separate the updating of retrieval dates (which can now go there) from the removal of existing references, i.e. this ticket #15.

re STRICT_KEEP_APPEND, I think a global ref mode may not be the way to go - we probably need something closer to statement level.

**Comment by tarrow** [comment]
@stuppie I think the changes in b4ecb175f7144d1a2f5cebc15fb6eb4b5393786e stops removing existing references.

However it doesn't append a second reference pointing to EuPMC if the existing reference is not from EuPMC. This may not be a problem. I think it is a matter of taste.

**Comment by Daniel-Mietchen** [comment]
Here's another pattern where existing references are being removed:
https://www.wikidata.org/w/index.php?title=Q29618689&diff=prev&oldid=513396587 .
In this case, the existing data even had a pointer to the exact API call used, which is probably something that would be useful for WDI to do as well &mdash; I just opened #29 for that.
