### ISSUE TITLE
build is failing according to the readme badge

### ISSUE THREAD

**Issue by matkoniecz** [SuLab/WikidataIntegrator#162]
https://github.com/SuLab/WikidataIntegrator#wikidata-integrator

**Comment by LeMyst** [comment]
The issue is here https://github.com/SuLab/WikidataIntegrator/blob/adb041eeb8d509908eaeda1d02dc9daf383fcd67/wikidataintegrator/tests/test_fastrun.py#L33
and it's because ProteinBoxBot removed the P31 (instance of): https://www.wikidata.org/w/index.php?title=Q10874&diff=1310966329&oldid=1310509685
The test must be changed but the error is not because of WDI code.
