### ISSUE TITLE
Error when installing on default Google Colab enviornment.

### ISSUE THREAD

**Issue by mmayers12** [SuLab/WikidataIntegrator#171]
I discovered that wikidataintegrator won't install to the default environment on Google Colab. Colab uses Python 3.6.9 as default, but WDI has a dependency (pyshexc) that requires Python>=3.7.  

I don't know if out of the box Google Colab compatibility is a priority for WDI, but right now it's broken.

**Comment by andrawaag** [comment]
Thanks for raizing this issue. I was aware of the issue but did not dive into the why and how's. The main issue - as you indicate, is that WDI is not backward compatible with version 3.6. I am discussing with @hsolbrig if we could - at least for the pyshex library, make that backward compatible. This issue applies also to [PAWS](https://hub.paws.wmcloud.org/hub/login) the jupyter hub for Wikimedia projects. There exists a [phabricator issue](https://phabricator.wikimedia.org/T265957) that suggests that an upgrade to 3.7 for paws is being discussed. 

I currently use a [docker version of jupyte](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html) to run notebooks. It is suboptimal because the beauty of both colab and paws is that it allows sharing notebook results.

**Comment by andrawaag** [comment]
closing this issue because it is currently fixed, since collab is using a (higher) compatible version of python
