### ISSUE TITLE
Added author name strings are duplicate in two ways

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SuLab/WikidataIntegrator#19]
In 
https://www.wikidata.org/w/index.php?title=Q28088911&diff=next&oldid=477781015 ,
the author name string "Wladek Minor" has been added *twice* (with series ordinal 2 and 3)
when there was no need to add it at all, since the P2093 statement on that item had already been correctly converted to a P50 one (with the correct series ordinal 2).

**Comment by stuppie** [comment]
@Daniel-Mietchen The [api response](http://www.ebi.ac.uk/europepmc/webservices/rest/search?query=PMC5331460&resulttype=core&format=json) has "Wladek Minor" as an author twice, as # 2 and 3. This looks to be a mistake on EuropePMCs end. I don't see any way to work around this, because we can not tell if the author is duplicated or if there are two authors with the same name. What makes this mistake even worse is that the ORCID ids for "Wladek Minor"#2 and #3 are different! Suggesting they are in fact two different people (when they're not). 

Regarding author name string vs author, WDI is checking for authors using ORCID IDs. In this case, the item for [Wladek Minor](https://www.wikidata.org/wiki/Q28028610) does not have an orcid ID, and so we can't know whether it is the correct item. In cases where the author item has an orcid ID (in wikidata) and it matches the orcid id from europePMC, it should not duplicate them.

**Comment by Daniel-Mietchen** [comment]
OK, I see why adding #3 is hard to avoid if the source has it that way, but if the P50 statement has the series ordinal (P1545) of #2, then adding a P2093 statement under #2093 should be simple to avoid.

**Comment by stuppie** [comment]
https://github.com/SuLab/WikidataIntegrator/commit/42d5d091e9978a1a86fb614a6d0659b3d87e1000
