### ISSUE TITLE
wdi_helpers.PubmedItem: Remove trailing period from title/ label

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SuLab/WikidataIntegrator#20]
Fatameh usually puts a period at the end of label and title and even "corrects" correct labels/ titles without that period.

In most cases, this period should not be there, e.g. in
https://www.wikidata.org/w/index.php?title=Q28088911&diff=next&oldid=477781015 .

In some (way fewer) cases, it actually should be there, since it is part of an abbreviation, e.g. as in
https://www.wikidata.org/wiki/Q30829915 .

In yet fewer cases, it is not (and should not be) there because there is another punctuation mark, e.g. a question mark, as in https://www.wikidata.org/wiki/Q30829948 .

**Comment by stuppie** [comment]
In the [API response](http://www.ebi.ac.uk/europepmc/webservices/rest/search?query=PMC5331460&resulttype=core&format=json), the title ends with a period, and so that is what we use. I just sent an email to the EuropePMC helpdesk asking for them to clarify what the policy is. I don't see an easy way to fix this without writing logic that detects whether a word is an abbreviation or not (which I can foresee having many edge cases)..

**Comment by Daniel-Mietchen** [comment]
OK, so what about checking with Crossref and PMC in cases where the item has more than one of {PMID, PMCID, DOI}? Both of them do not seem to use the period at the end:
https://api.crossref.org/v1/works/http://dx.doi.org/10.1107/S2052252516020364
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC5331460 .

So a simple heuristic could just be to keep a period at the end if at least two of these up to three different sources agree that there should be one.

**Comment by Daniel-Mietchen** [comment]
Edge case: title is in brackets because original language is not English, e.g. as in https://www.wikidata.org/wiki/Q30833499 .

**Comment by tarrow** [comment]
Hm.. This adds quite some complexity (and time to run etc..) if we have to check all three.

I think a good start would be to not 'correct' by adding the period to an existing title if that is the only difference. This should be much easier

**Comment by Daniel-Mietchen** [comment]
Yes, not 'correcting' correct titles is a good first step. 
The [policy on punctuation](https://www.wikidata.org/wiki/Help:Description#Punctuation) is clear:
```
Descriptions are not full sentences, and should not end in periods/full stops.
```

**Comment by stuppie** [comment]
See https://github.com/SuLab/WikidataIntegrator/commit/9bcadf9f7575760ea3e69b3b3de3da13e06e4594
If a current title is 90% or more similar to the proposed new title, it won't be changed. @tarrow Please pull to fatameh

**Comment by stuppie** [comment]
@Daniel-Mietchen I emailed PMC to ask about the punctuation. This is the reply:

> Dear Gregory,
> 
> Thanks for your email. All records we receive from PubMed will end with punctuation. If there is not a period/other punctuation at the end of the title they add in a period:
> 
> https://www.ncbi.nlm.nih.gov/pubmed/?term=PMC5331460
> 
> I hope this answers your question.
> 
> Best wishes,
> 
> Fran
> 
> --
> Frances Rogers
> 
> Europe PMC Helpdesk
> Email: helpdesk@europepmc.org
> Tel: +44 (0)1223 494 118
> http://europepmc.org
> 

I don't think this is a big enough issue to justify the work required to switch APIs, for now, and I don't know how to handle all of the punctuation edge cases...

**Comment by Daniel-Mietchen** [comment]
I guess the 90% workaround may be good enough for this one for now, but I just brought up the issue of API switching in https://github.com/SuLab/WikidataIntegrator/issues/26#issuecomment-312958768 for other reasons.

**Comment by tarrow** [comment]
@stuppie I can pull to fatameh most easily once the new code is realised to pypy. Would that be possible to do? If its a big hassle I can work around it but using pypy is probably preferable.

Thanks for fixing this bug too!

**Comment by moqri** [comment]
@Daniel-Mietchen I'm removing the trailing dots from the title of all PMC articles:
https://www.wikidata.org/wiki/Special:Contributions/Mahdimoqri

Have you found any way to find all PMC articles belonging to your second category? 
"In some (way fewer) cases, it actually should be there, since it is part of an abbreviation, e.g. as in
https://www.wikidata.org/wiki/Q30829915 ."

I will remove them from my list or undo my correction on them if there is anyway to get a list of them.

**Comment by moqri** [comment]
Thanks @zuphilip , I'm going to add the x=1 filter to exclude the trailing .*. patters (which take cares of words like U.S.A.

For larger x values, I' m not sure if it's a good idea since the false positive are much bigger than true positive. For example, for x=3 all the titles ending with a three-letter long words would be excluded from my list which is not desirable.

**Comment by moqri** [comment]
The problem with asterisks are less severe (at least in PMC). There are currently around 700 items with titles with trailing asterisk on Wikidata (1 in 5000). 

With the help of these wonderful [people](https://www.wikidata.org/wiki/Wikidata:Request_a_query#List_of_all_scientific_articles_with_a_PMCID_and_a_title_with_a_trailing_asterisk_and_a_dot_%28%2A.%29), I could find the all. Putting them [here](https://github.com/moqri/wikidata_scientific_citations/blob/master/fatameh_sister_bot/pmc_trailing_asterisk.csv) for reference.

**Comment by moqri** [comment]
This is my proposal for removing the trailing periods in titles and labels:

https://github.com/moqri/WikidataIntegrator/commit/10e8687e9bf600eb2259f7b03842188f83845861#diff-f1961af53d0d701209a52bb87df8a698

**Comment by stuppie** [comment]
Added comments on the code. Copying third comment here:
This doesn't address any other acronyms, like
Role of grey squirrels and pheasants in the transmission of Borrelia burgdorferi sensu lato, the Lyme disease spirochaete, in the U.K. (Q48545658)
or
Powdery mildews on lilac in western North America include Phyllactinia syringae, sp. nov. (Q30829915)

**Comment by moqri** [comment]
This is to fix the trailing dot (period), so we assume the title has a trailing dot e.g. "Sharing Big Data."
original_title="Sharing Big Data."
original_title[-1] is "."
original_title[-3] is "t"
therefore the condition is satisfied and the trailing dot will be removed from the title.

For the title "Role of grey squirrels and pheasants in the transmission of Borrelia burgdorferi sensu lato, the Lyme disease spirochaete, in the U.K." , since original_title[-3] is "." my code will not remove the trailing dot.

**Comment by moqri** [comment]
For the extremely rare cases of titles ending with an abbreviated words not in the forms of X.Y.Z (such as nov.), my current code will remove the trailing dot.
