### ISSUE TITLE
Feature request: validate lexemes using shex

### ISSUE THREAD

**Issue by dpriskorn** [SuLab/WikidataIntegrator#200]
as a user I would like to ensure a lexeme validate against an entity schema

**Comment by andrawaag** [comment]
Currently, the WikidataIntegrator does not support updating and adding lexemes. The reason is that the data model of the wikidata item for lexemes differs from the item ones. 
In principle adding support to validate lexemes using shex would be kind of straightforward, but first WDLexemeEngine would need to be built inside the WikidataIntegrator. 

I am aware of lexemes but I am not a regular curator of lexemes, so it would take me quite some effort to write the WDLexemeEngine and while I would love to do it, I currently don't have the bandwidth to do so. 

Anyone with solid knowledge on the data model of lexemes in Wikidata might be able to copy WDItemEngine in wdi_core and extend this library with WDLexemeEngine. Once that is done, validation support should be readily available.

**Comment by dpriskorn** [comment]
WDI supports lexemes since a few versions. I have asked that dev to add validation functionality
