### ISSUE TITLE
Updating of retrieval dates

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SuLab/WikidataIntegrator#25]
This issue was partly discussed in #15, but since it is a separate issue and still a problem ([recent example](https://www.wikidata.org/w/index.php?title=Q24527226&diff=prev&oldid=512477212)), I'm opening a separate ticket, also to facilitate work on #24.

**Comment by tarrow** [comment]
For those following along at home this seems to be fixed in b4ecb175f7144d1a2f5cebc15fb6eb4b5393786e :)

Currently (and probably forever) I don't think there is a good way to automatically update fatameh to use the latest code from WDI master so there'll always be some lag between when things are fixed here and they go live other places. 

@stuppie I think this can be closed :) thanks!

**Comment by stuppie** [comment]
Thanks @tarrow, Yes. Should be fixed. I'll lyk when you should update Fatameh in the future
