### ISSUE TITLE
Duplicate author name string on same paper

### ISSUE THREAD

**Issue by Daniel-Mietchen** [SuLab/WikidataIntegrator#42]
Some items have the same author name string several times. Usually this is because of some conferences putting all authors of conference contributions into one giant list on a "paper" about the conference, and people who have made multiple contributions simply appear multiple times.

However, there are also cases where the same author string appears multiple times for no apparent reason. One example is Tomáš Olejár in
https://www.wikidata.org/w/index.php?title=Q33837416&oldid=528259570 .

I noticed this by way of https://tools.wmflabs.org/sourcemd/new_resolve_authors.php?fuzzy=0&name=Tom%C3%A1%C5%A1+Olej%C3%A1r and fixed it for the two of those five papers for which he simply was last author. In the other cases, the series ordinal for authorship order would have to be adjusted as well.

Given that all his articles were affected, I suspect there may be some mishandling of the non-ASCII characters in his name.

**Comment by stuppie** [comment]
@Daniel-Mietchen 
This example is because it is listed twice in europePMC. 
http://europepmc.org/abstract/med/25009615
It looks as if this author has two different ORCID IDs (bottom of the page) and so he gets treated as two different people with the same name. I will update the tool to include the reference URL in the references so its clear where this data comes from.

Could you give me an example of the first issue?
