### ISSUE TITLE
item_name doesn't do anything

### ISSUE THREAD

**Issue by stuppie** [SuLab/WikidataIntegrator#73]
item_name isn't really used (its only checked to be not empty), but isn't used to retrieve an item or set its label. Probably confusing to new users and should be removed.

**Comment by Samwalton9** [comment]
I was stumped for a while today about both this and domain. Checked the code and it seems to do nothing, so agree with removal if it's not used.

**Comment by andrawaag** [comment]
It actually does more than only checking to be not empty. If it is empty, together with the domain argument a new Wikidata item is issued:

`        if self.item_name and self.domain is None and len(self.data) > 0:
            self.create_new_item = True
            self.__construct_claim_json()
`
line 191

I agree that this is confusing and should be removed, but since it creates a new item, this function might be used by WDI users.

**Comment by andrawaag** [comment]
item_name and domain parameter have been removed with version 0.2.0

**Comment by andrawaag** [comment]
addressed in https://github.com/SuLab/WikidataIntegrator/commit/4c8c294bd0285f8ac25e0cd1491e32699ffab6ea

**Comment by andrawaag** [comment]
addressed in: 
* https://github.com/SuLab/WikidataIntegrator/commit/69d6a20b349cfad843f55b1e4a2399c1b42fb567
* https://github.com/SuLab/WikidataIntegrator/commit/e5865fdb52e18c0cf1057eced415d6893982e85e
* https://github.com/SuLab/WikidataIntegrator/commit/3fb9c457b48804858af0635c0a78b14fc8242c03
