### ISSUE TITLE
UA should include name of Bot being operated

### ISSUE THREAD

**Issue by addshore** [SuLab/WikidataIntegrator#75]
Right now the default UA is simply "wikidataintegrator: github.com/SuLab/WikidataIntegrator"

In relation to https://phabricator.wikimedia.org/T199662 it would be great if when operated as part of a bot the bot name or user was automatically included as part of the UA.

Other libraries and bots already seem to do this such as Pywikibot

**Comment by stuppie** [comment]
Do you have a suggested format?

**Comment by stuppie** [comment]
Currently users can already set their own user-agent upon initialization (https://github.com/SuLab/WikidataIntegrator/blob/9ba41fab73ba34fe5a2b13a07dab09efbdb7ba2f/wikidataintegrator/wdi_core.py#L58).
This isn't required though. I could change it so that if the user logs in with a username and password, their username gets added to the UA. However, with the caveat if they log in using oath, it wouldn't be there. How does pywikibot get the tool name? Does it require users to set their UA before they can run?
