### ISSUE TITLE
Versions after 0.555 break compatibility with older bots due to get_distinct_value_props().

### ISSUE THREAD

**Issue by dcodings** [SuLab/WikidataIntegrator#81]
The new versions after 0.555 seems to break compatibility with older bots because now the __init__() method of wdi_coreWDItemEngine calls get_distinct_value_props() and that one automatically raises an exception as old bots do not have core_props among the parameters of wdi_coreWDItemEngine (so by default core_props=None). The raised exception is not captured as before it was not present, and so bots stop.

Moreover, the solutions to avoid the exception raising in get_distinct_value_props() seem to be (from the Exception message in the code)
1) users have to "set P2302 and Q21502410 in your[their] wikibase", which may not be possible for certain users. 
2) "set `core_props` manually": but if one does not want core_props, and so sets core_props=[] or None or something similar, than the exception will be raised and the bot will never run. 

Is it possible to make core_props optional and don't call get_distinct_value_props() necessarily? Thanks.

**Comment by stuppie** [comment]
Hmm.. ya. I see, so you are running on a wikibase and don't want any core_props? I quick fix would be to change [line 165](https://github.com/SuLab/WikidataIntegrator/blob/bf5981536c5c855edeef1e655db48d28f7e6f934/wikidataintegrator/wdi_core.py#L165) to check if `core_props` is None, instead of `not core_props`, that way you can pass an empty list/set, and it will run. I'll make that change. Will this solve the problem? 

You can also, in the meantime, as a quick workaround, just set core_props to something that doesn't exist (i.e. `core_props={"Pxxx"}`).

And also, we should be using semantic versioning, because, as you said, it breaks compatibility, so I should have bumped the minor version and not the micro version.

**Comment by dcodings** [comment]
Hi, unfortunately this workaround will not help in my situation because the bots I'm using will not easily be reconfigurable to specify core_props in that way for the items. 

I think the right solution should be that you call get_distinct_value_props() **only IF core_props is NOT None or empty**: that is, the contrary logic to what is now in the code (in this way you make core_props optional and not mandatory). 

In this way only people that want/need core_props will use the new checks. The logic you put in the code forces users to functionalities they do not necessarily want (and whose exceptions they did not have to check for in the past, hence breaking code).

**Comment by stuppie** [comment]
I've changed it to not fail if core_props can't be determined: 
https://github.com/SuLab/WikidataIntegrator/commit/d4b18de7ce62093af17c125e20b315dbdb3d1d11
